version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'shouts.dev/laravel'
    container_name: shouts-laravel-app
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html
    networks:
      backend:
        aliases:
          - laravel-app
    depends_on:
      - mysql
  mysql:
    image: 'mysql:latest'
    container_name: shouts-laravel-db
    restart: unless-stopped
    ports:
      - "3305:3306"
    environment:
      MYSQL_DATABASE: 'laravel'
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./run/var:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      backend:
        aliases:
          - app-db

networks:
  backend:
    name: backend-network
