version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pos-app
    env_file:
      - .env
    ports:
      - "8085:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - pos-network

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - pos-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8086:80"
    environment:
      PMA_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - pos-network

networks:
  pos-network:
    driver: bridge

volumes:
  db-data:
